# Generated by Django 6.0.4 on 2026-04-16 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('BASIC', 'Basic $30'), ('PRO', 'Pro $40'), ('ELITE', 'Elite $50')], max_length=10)),
                ('amount', models.FloatField()),
                ('currency', models.CharField(default='USD', max_length=5)),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('mpesa_code', models.CharField(blank=True, max_length=30)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
    ]
