# Generated by Django 6.0.4 on 2026-04-21 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='mmdeuser',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='mmdeuser',
            name='google_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mmdeuser',
            name='subscription_plan',
            field=models.CharField(choices=[('FREE', 'Free'), ('BASIC', 'Basic $30')], default='FREE', max_length=20),
        ),
    ]
