# Generated by Django 6.0.4 on 2026-04-23 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmde_gateway', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradingViewFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_secret', models.CharField(default='default', max_length=100)),
                ('symbol', models.CharField(max_length=20)),
                ('interval', models.CharField(max_length=10)),
                ('market', models.CharField(default='forex', max_length=20)),
                ('candles_json', models.TextField()),
                ('received_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
    ]
