# Generated by Django 6.0.4 on 2026-04-21 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('FREE', 'Free'), ('BASIC', 'Basic — $30/mo'), ('PRO', 'Pro — $40/mo'), ('ELITE', 'Elite — $50/mo')], max_length=10, unique=True)),
                ('display_name', models.CharField(max_length=50)),
                ('price_usd', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('allowed_markets', models.JSONField(default=list, help_text='e.g. ["forex","gold","indices","crypto","stocks"]')),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Subscription Plan',
                'verbose_name_plural': 'Subscription Plans',
                'ordering': ['price_usd'],
            },
        ),
    ]
